# Generated by Django 4.0 on 2021-12-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longLink', models.CharField(max_length=250, verbose_name='Полная ссылка')),
                ('shortLink', models.CharField(max_length=50, verbose_name='Сокращенная ссылка')),
                ('user', models.ForeignKey(help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
