# Generated by Django 4.0 on 2021-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.CharField(max_length=50, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
