# Generated by Django 4.0 on 2021-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_link_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.SlugField(unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
