# Generated by Django 4.0 on 2021-12-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_link_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longLink',
            field=models.CharField(max_length=250, unique=True, verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.SlugField(max_length=10, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
