# Generated by Django 4.0 on 2021-12-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_link_longlink_alter_link_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longLink',
            field=models.CharField(max_length=250, verbose_name='Полная ссылка'),
        ),
    ]
