# Generated by Django 4.0 on 2021-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longLink',
            field=models.CharField(max_length=160, verbose_name='Полная ссылка'),
        ),
    ]
