# Generated by Django 4.0 on 2021-12-27 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_link_longlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 19, 28, 7, 597997, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
