# Generated by Django 4.0 on 2021-12-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_link_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='date',
        ),
    ]
