# Generated by Django 4.0 on 2022-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_link_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Моя ссылка', 'verbose_name_plural': 'Мои ссылки'},
        ),
        migrations.AlterField(
            model_name='link',
            name='longLink',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
