# Generated by Django 4.0 on 2022-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_link_options_alter_link_longlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longLink',
            field=models.CharField(max_length=160, verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.SlugField(max_length=10, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
