# Generated by Django 4.0 on 2022-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_link_longlink_alter_link_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(default='переход на ...', max_length=200, verbose_name='Описание страницы перехода'),
        ),
    ]
