# Generated by Django 4.0 on 2021-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='default.png', upload_to='work_images')),
            ],
        ),
    ]
