# Generated by Django 4.0 on 2021-12-27 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.AddField(
            model_name='job',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Окончание работы'),
        ),
        migrations.AddField(
            model_name='job',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало работы'),
        ),
    ]
