# Generated by Django 4.0 on 2021-12-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_job_date_job_date_end_job_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.URLField(default='www'),
        ),
    ]
